from typing import List, Dict

SOURCES: List[Dict] = [
    {
        "id": "dinamalar",
        "name": "Dinamalar Crime",
        "type": "html",
        "url": "https://www.dinamalar.com/crime_news",
        "language": "ta",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "ul.news_list li, div.news-card, div.story-list li",
            "title": "a[itemprop='url'], a",
            "link": "a[itemprop='url'], a",
            "summary": "p, div.news_desc",
            "time": "span.time, time",
            "image": "img[src]",
        },
    },
    {
        "id": "vikatan",
        "name": "Vikatan Tamil Nadu",
        "type": "html",
        "url": "https://www.vikatan.com/news/tamilnadu",
        "language": "ta",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "div.story-card, div.story, article",
            "title": "h2.story-title, h3.story-title, a",
            "link": "a.story-link[href], a[href]",
            "summary": "p.story-summary, p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },
    {
        "id": "maalaimalar",
        "name": "Maalai Malar",
        "type": "html",
        "url": "https://www.maalaimalar.com/district",
        "language": "ta",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "div.news-item, div.list-item, article",
            "title": "h3 a, a",
            "link": "h3 a[href], a[href]",
            "summary": "p, div.description",
            "time": "span.time, time",
            "image": "img[src]",
        },
    },
    {
        "id": "thesouthfirst",
        "name": "The South First",
        "type": "html",
        "url": "https://thesouthfirst.com/category/tamil-nadu/crime/",
        "language": "en",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "article.post, div.post",
            "title": "h2.entry-title, a",
            "link": "h2.entry-title a[href], a[href]",
            "summary": "div.entry-summary p, p",
            "time": "time.entry-date, span.date",
            "image": "img[src]",
        },
    },
    {
        "id": "dtnext",
        "name": "DT Next",
        "type": "html",
        "url": "https://www.dtnext.in/topic/tamil-nadu/crime/",
        "language": "en",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "article, div.post-preview, div.story",
            "title": "h2.entry-title, a",
            "link": "h2.entry-title a[href], a[href]",
            "summary": "div.entry-summary p, p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },
    {
        "id": "indiatoday_tn",
        "name": "India Today Tamil Nadu",
        "type": "rss",
        "url": "https://www.indiatoday.in/rss/1206.xml",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "newindianexpress_tn",
        "name": "New Indian Express TN",
        "type": "rss",
        "url": "https://www.newindianexpress.com/states/tamil-nadu/rssfeed/?id=170&getXmlFeed=true",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_crime",
        "name": "Google News TN Crime",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+crime&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "thehindu_tn",
        "name": "The Hindu Tamil Nadu",
        "type": "rss",
        "url": "https://www.thehindu.com/news/states/tamil-nadu/feeder/default.rss",
        "language": "en",
        "tier": 1,
        "interval_min": 20,
        "selectors": {
            "content": "div.article-text, div.storyline, div.article__content, section.article-content",
        },
    },
    {
        "id": "thenewsminute_tn",
        "name": "The News Minute Tamil Nadu",
        "type": "rss",
        "url": "https://www.thenewsminute.com/tamil-nadu/feed",
        "language": "en",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "google_news_tn_police",
        "name": "Google News TN Police",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+police+arrested&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_district",
        "name": "Google News TN Districts",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+district+incident&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_murder",
        "name": "Google News TN Murder/Assault",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+murder+OR+assault+OR+stabbed&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_drugs",
        "name": "Google News TN Narcotics",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+ganja+OR+drugs+seized+OR+narcotics&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "ndtv_tn_crime",
        "name": "NDTV Tamil Nadu Crime",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=site:ndtv.com+Tamil+Nadu+crime&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "ndtv_tn_news",
        "name": "NDTV Tamil Nadu News",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=site:ndtv.com+Tamil+Nadu&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "puthiyathalaimurai",
        "name": "Puthiya Thalaimurai",
        "type": "html",
        "url": "https://www.puthiyathalaimurai.com/district-news",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
        "selectors": {
            "articles": "div.news-list li, article, div.story-card",
            "title": "h2 a, h3 a, a",
            "link": "a[href]",
            "summary": "p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },
    {
        "id": "polimernews",
        "name": "Polimer News Tamil Nadu",
        "type": "html",
        "url": "https://www.polimernews.com/category/tamilnadu",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
        "selectors": {
            "articles": "article, div.news-card, div.list-item",
            "title": "h2 a, h3 a, a",
            "link": "a[href]",
            "summary": "p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },
]
