from typing import List, Dict

SOURCES: List[Dict] = [
    {
        "id": "dinamalar",
        "name": "Dinamalar Crime",
        "type": "html",
        "url": "https://www.dinamalar.com/crime_news",
        "language": "ta",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "ul.news_list li, div.news-card, div.story-list li",
            "title": "a[itemprop='url'], a",
            "link": "a[itemprop='url'], a",
            "summary": "p, div.news_desc",
            "time": "span.time, time",
            "image": "img[src]",
        },
    },
    {
        "id": "vikatan",
        "name": "Vikatan Tamil Nadu",
        "type": "html",
        "url": "https://www.vikatan.com/news/tamilnadu",
        "language": "ta",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "div.story-card, div.story, article",
            "title": "h2.story-title, h3.story-title, a",
            "link": "a.story-link[href], a[href]",
            "summary": "p.story-summary, p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },
    {
        "id": "maalaimalar",
        "name": "Maalai Malar",
        "type": "html",
        "url": "https://www.maalaimalar.com/district",
        "language": "ta",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "div.news-item, div.list-item, article",
            "title": "h3 a, a",
            "link": "h3 a[href], a[href]",
            "summary": "p, div.description",
            "time": "span.time, time",
            "image": "img[src]",
        },
    },
    {
        "id": "thesouthfirst",
        "name": "The South First",
        "type": "html",
        "url": "https://thesouthfirst.com/category/tamil-nadu/crime/",
        "language": "en",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "article.post, div.post",
            "title": "h2.entry-title, a",
            "link": "h2.entry-title a[href], a[href]",
            "summary": "div.entry-summary p, p",
            "time": "time.entry-date, span.date",
            "image": "img[src]",
            "url_filter": "/tamilnadu/",
        },
    },
    {
        "id": "dtnext",
        "name": "DT Next",
        "type": "html",
        "url": "https://www.dtnext.in/topic/tamil-nadu/crime/",
        "language": "en",
        "tier": 1,
        "interval_min": 15,
        "selectors": {
            "articles": "article, div.post-preview, div.story",
            "title": "h2.entry-title, a",
            "link": "h2.entry-title a[href], a[href]",
            "summary": "div.entry-summary p, p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },
    {
        "id": "indiatoday_tn",
        "name": "India Today Tamil Nadu",
        "type": "rss",
        "url": "https://www.indiatoday.in/rss/1206.xml",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "newindianexpress_tn",
        "name": "New Indian Express TN",
        "type": "rss",
        "url": "https://www.newindianexpress.com/states/tamil-nadu/rssfeed/?id=170&getXmlFeed=true",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_crime",
        "name": "Google News TN Crime",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+crime&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "thehindu_tn",
        "name": "The Hindu Tamil Nadu",
        "type": "rss",
        "url": "https://www.thehindu.com/news/states/tamil-nadu/feeder/default.rss",
        "language": "en",
        "tier": 1,
        "interval_min": 20,
        "selectors": {
            "content": "div.article-text, div.storyline, div.article__content, section.article-content",
        },
    },
    {
        "id": "thenewsminute_tn",
        "name": "The News Minute Tamil Nadu",
        "type": "rss",
        "url": "https://www.thenewsminute.com/tamil-nadu/feed",
        "language": "en",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "google_news_tn_police",
        "name": "Google News TN Police",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+police+arrested&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_district",
        "name": "Google News TN Districts",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+district+incident&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_murder",
        "name": "Google News TN Murder/Assault",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+murder+OR+assault+OR+stabbed&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_drugs",
        "name": "Google News TN Narcotics",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+ganja+OR+drugs+seized+OR+narcotics&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "ndtv_tn_crime",
        "name": "NDTV Tamil Nadu Crime",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=site:ndtv.com+Tamil+Nadu+crime&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "ndtv_tn_news",
        "name": "NDTV Tamil Nadu News",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=site:ndtv.com+Tamil+Nadu&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "puthiyathalaimurai",
        "name": "Puthiya Thalaimurai",
        "type": "html",
        "url": "https://www.puthiyathalaimurai.com/district-news",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
        "selectors": {
            "articles": "div.news-list li, article, div.story-card",
            "title": "h2 a, h3 a, a",
            "link": "a[href]",
            "summary": "p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },
    {
        "id": "polimernews",
        "name": "Polimer News Tamil Nadu",
        "type": "html",
        "url": "https://www.polimernews.com/category/tamilnadu",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
        "selectors": {
            "articles": "article, div.news-card, div.list-item",
            "title": "h2 a, h3 a, a",
            "link": "a[href]",
            "summary": "p",
            "time": "time, span.date",
            "image": "img[src]",
        },
    },

    # ── Regional Tamil newspapers ────────────────────────────────────────────
    {
        "id": "dinakaran",
        "name": "Dinakaran",
        "type": "rss",
        "url": "https://www.dinakaran.com/rss.xml",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "dailythanthi_crime",
        "name": "Daily Thanthi Crime",
        "type": "rss",
        "url": "https://www.dailythanthi.com/rss/crime",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "oneindia_tamil_crime",
        "name": "One India Tamil Crime",
        "type": "rss",
        "url": "https://tamil.oneindia.com/rss/crime/",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "oneindia_tamil_tn",
        "name": "One India Tamil Nadu",
        "type": "rss",
        "url": "https://tamil.oneindia.com/rss/tamilnadu/",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "news18_tamil",
        "name": "News18 Tamil Nadu",
        "type": "rss",
        "url": "https://tamil.news18.com/commonfeeds/v1/ta/rss/crime-news.xml",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "samayam_tamil",
        "name": "Samayam Tamil",
        "type": "rss",
        "url": "https://tamil.samayam.com/rss/news/crime/tvid-2300.cms",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
    },
    {
        "id": "abp_nadu",
        "name": "ABP Nadu",
        "type": "html",
        "url": "https://www.abpnadu.com/tamilnadu",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
        "selectors": {
            "articles": "div.story-card, article, div.widget_story",
            "title": "h2 a, h3 a, a",
            "link": "a[href]",
            "summary": "p",
            "time": "time, span.date",
            "image": "img[src]",
            "url_filter": "/tamilnadu/",
        },
    },
    {
        "id": "dinamani",
        "name": "Dinamani",
        "type": "rss",
        "url": "https://www.dinamani.com/rss/tamil-news/crime/sid1/",
        "language": "ta",
        "tier": 1,
        "interval_min": 20,
    },

    # ── NewsAPI (requires NEWSAPI_KEY in config/.env) ────────────────────────
    {
        "id": "newsapi_tn",
        "name": "NewsAPI Tamil Nadu",
        "type": "newsapi",
        "language": "en",
        "tier": 1,
        "interval_min": 60,
        "window_hours": 65,    # slight overlap
    },

    # ── GDELT live feed ──────────────────────────────────────────────────────
    {
        "id": "gdelt_live",
        "name": "GDELT Live",
        "type": "gdelt",
        "language": "en",
        "tier": 2,
        "interval_min": 60,       # poll every 60 min; window covers last 60 min
        "window_minutes": 70,     # slight overlap to avoid gaps
    },

    # ── Civic / Infrastructure / Public Grievance feeds ──────────────────────
    {
        "id": "google_news_tn_civic",
        "name": "Google News TN Civic Issues",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+civic+OR+corporation+OR+panchayat+OR+grievance&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 45,
    },
    {
        "id": "google_news_tn_infrastructure",
        "name": "Google News TN Infrastructure",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+road+OR+water+supply+OR+electricity+OR+infrastructure+problem&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 45,
    },
    {
        "id": "google_news_tn_accident",
        "name": "Google News TN Accidents",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=Tamil+Nadu+accident+OR+fire+OR+flood+OR+collapse&hl=en-IN&gl=IN&ceid=IN:en",
        "language": "en",
        "tier": 2,
        "interval_min": 30,
    },
    {
        "id": "google_news_tn_tamil_crime",
        "name": "Google News TN Tamil Crime",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AF%8D%E0%AE%A8%E0%AE%BE%E0%AE%9F%E0%AF%81+%E0%AE%95%E0%AF%81%E0%AE%B1%E0%AF%8D%E0%AE%B1%E0%AE%AE%E0%AF%8D&hl=ta&gl=IN&ceid=IN:ta",
        "language": "ta",
        "tier": 2,
        "interval_min": 30,
    },
]
